version: "3"
services:
    backend:
        image: node:8.11.4
        restart: always
        container_name: node_pokemon
        volumes:
            - .:/backend
            - /node_modules
        depends_on:
            - mongodb
        ports:
            - 3000:3000
        command: bash -c "cd /backend &&  node_modules/.bin/nodemon app.js"

    mongodb:
        image: mongo:latest
        restart: always
        container_name: mongo_pokemon
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod
